### ISSUE TITLE
Cannot redefine property: find (incompatibility with connect-rest)

### ISSUE THREAD

**Issue by cperryk** [victorquinn/memcache-plus#2]
I'm noticing that this throws an error if I attempt to require it _after_ requiring connect-rest. To reproduce, run this script:
```
var rest = require('connect-rest');
var memcached_plus = require('memcache-plus');
```

Here's the error on my machine:
```
TypeError: Cannot redefine property: find
    at Function.defineProperty (native)
    at define (/Users/kirkcp/Documents/interactives/express/node_modules/memcache-plus/node_modules/collections/shim-array.js:56:12)
    at Object.<anonymous> (/Users/kirkcp/Documents/interactives/express/node_modules/memcache-plus/node_modules/collections/shim-array.js:135:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kirkcp/Documents/interactives/express/node_modules/memcache-plus/node_modules/collections/generic-collection.js:272:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by victorquinn** [comment]
Turns out this was an issue with the "collections" package and its use of a shim. This was also pointed out in #25 

I have updated Memcache Plus to not use the "collections/deque" as the queueing mechanism which should fix this issue.
