### ISSUE TITLE
RangeError when trying to use autodiscover

### ISSUE THREAD

**Issue by AndrewIngram** [victorquinn/memcache-plus#30]
I've tried this in Node versions 4.6.1, 6.2.0, 6.5.0 and 6.9.0:

```
new MemcachePlus({hosts: [/* my autodiscover endpoint */], autodiscover: true});
```

My endpoint is of the format: `something.cfg.use1.cache.amazonaws.com`, i've tried it with and without adding the port (11211) to the end.

I get this exception:

```
> TypeError: Cannot read property 'key' of undefined
    at Connection.read (/opt/web/node_modules/memcache-plus/lib/connection.js:262:34)
    at emitOne (events.js:96:13)
    at Carrier.emit (events.js:188:7)
    at /opt/web/node_modules/memcache-plus/node_modules/carrier/lib/carrier.js:24:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
> Unhandled rejection RangeError: "port" option should be >= 0 and < 65536: undefined
    at lookupAndConnect (net.js:959:13)
    at Socket.connect (net.js:934:5)
    at Object.exports.connect.exports.createConnection (net.js:74:35)
    at Connection.connect (/opt/web/node_modules/memcache-plus/lib/connection.js:186:27)
    at new Connection (/opt/web/node_modules/memcache-plus/lib/connection.js:136:10)
    at Client.<anonymous> (/opt/web/node_modules/memcache-plus/lib/client.js:186:34)
    at Array.forEach (native)
    at Client.connectToHosts (/opt/web/node_modules/memcache-plus/lib/client.js:181:16)
    at Client.<anonymous> (/opt/web/node_modules/memcache-plus/lib/client.js:169:14)
    at bound (domain.js:280:14)
    at Client.runBound (domain.js:293:12)
    at Client.tryCatcher (/opt/web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/web/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/web/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/web/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/web/node_modules/bluebird/js/release/promise.js:691:18)
```

**Comment by victorquinn** [comment]
Hmmm well that's certainly a bug.

Looking into it now, haven't noticed anything obvious jumping out at me though. Will update here once it's sorted! 
 
In the meantime (and this is totally not an ideal solution, I know) you could try reverting to an older version of the module such as 0.2.9 and see if that fixes the problem for you (temporarily at least).

**Comment by AndrewIngram** [comment]
I've tried 0.2.9, no luck, but different error.

I've just tried running the latest version with debugging enabled:

```
new require('memcache-plus')({hosts: '<<MYHOSTNAME>>'], autodiscover: true})
  memcache-plus:connection connecting to host <<MYHOSTNAME>> +0ms
Client {
  hosts: [ '<<MYHOSTNAME>>' ],
  autodiscover: true,
  bufferBeforeError: 1000,
  disabled: false,
  reconnect: true,
  onNetError: [Function: onNetError],
  queue: true,
  netTimeout: 500,
  backoffLimit: 10000,
  maxValueSize: 1048576,
  buffer: List [],
  connections: {} }
>   memcache-plus:connection successfully (re)connected! +25ms
  memcache-plus:connection starting autodiscovery +1ms
  memcache-plus:connection sending: "config get cluster" +2ms
  memcache-plus:connection got data: "CONFIG cluster 0 133" and the queue now has "1" elements +3ms
  memcache-plus:connection responded and the queue now has "1" elements +0ms
  memcache-plus:connection got data: "1" and the queue now has "1" elements +4ms
  memcache-plus:connection responded and the queue now has "1" elements +0ms
  memcache-plus:connection got data: "<<CORRECT MEMCACHED SERVERS>>" and the queue now has "1" elements +0ms
  memcache-plus:connection responded and the queue now has "1" elements +0ms
  memcache-plus:connection got data: "" and the queue now has "1" elements +0ms
  memcache-plus:connection responded and the queue now has "0" elements +1ms
  memcache-plus:connection got data: "END" and the queue now has "0" elements +0ms
TypeError: Cannot read property 'type' of undefined
    at Connection.read (/opt/web/node_modules/memcache-plus/lib/connection.js:262:21)
    at emitOne (events.js:77:13)
    at Carrier.emit (events.js:169:7)
    at /opt/web/node_modules/memcache-plus/node_modules/carrier/lib/carrier.js:24:12
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
>   memcache-plus:connection got autodiscovery response from elasticache +3ms
  memcache-plus:connection connecting to host localhost:undefined +1ms
Unhandled rejection RangeError: port should be >= 0 and < 65536: undefined
    at lookupAndConnect (net.js:944:13)
    at Socket.connect (net.js:921:5)
    at Object.exports.connect.exports.createConnection (net.js:69:35)
    at Connection.connect (/opt/web/node_modules/memcache-plus/lib/connection.js:186:27)
    at new Connection (/opt/web/node_modules/memcache-plus/lib/connection.js:136:10)
    at Client.<anonymous> (/opt/web/node_modules/memcache-plus/lib/client.js:186:34)
    at Array.forEach (native)
    at Client.connectToHosts (/opt/web/node_modules/memcache-plus/lib/client.js:181:16)
    at Client.<anonymous> (/opt/web/node_modules/memcache-plus/lib/client.js:169:14)
    at bound (domain.js:287:14)
    at Client.runBound (domain.js:300:12)
    at Client.tryCatcher (/opt/web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/web/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/web/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/web/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/web/node_modules/bluebird/js/release/promise.js:691:18)

```

**Comment by victorquinn** [comment]
Apologies for the long turnaround, but this should be fixed and I'll be pushing it to npm as 0.2.16!

**Comment by AndrewIngram** [comment]
Great, i'll give it a try as soon as it's available :)

**Comment by victorquinn** [comment]
Should be all set and live on npm!

**Comment by AndrewIngram** [comment]
It seems to be working, thanks a lot!
