### ISSUE TITLE
error when hosts array uses process.env for lambda/claudiajs

### ISSUE THREAD

**Issue by msolovyov** [victorquinn/memcache-plus#41]
`const mc = new memcached({hosts: [process.env.memcache], autodiscover: true})
`

babel src --out-dir bin

src/api.js -> bin/api.js
validating package
TypeError: Cannot read property 'split' of undefined
    at Client.splitHost (/private/var/folders/w4/0_jcj9dd67g3ycr39nbzp8kh0000gn/T/9b8b4587-e1c6-4219-a679-a574b6c692fc/node_modules/memcache-plus/lib/client.js:230:19)
    at Client.<anonymous> (/private/var/folders/w4/0_jcj9dd67g3ycr39nbzp8kh0000gn/T/9b8b4587-e1c6-4219-a679-a574b6c692fc/node_modules/memcache-plus/lib/client.js:153:22)
    at Array.map (native)
    at Client.getHostList (/private/var/folders/w4/0_jcj9dd67g3ycr39nbzp8kh0000gn/T/9b8b4587-e1c6-4219-a679-a574b6c692fc/node_modules/memcache-plus/lib/client.js:152:35)
    at Client.connect (/private/var/folders/w4/0_jcj9dd67g3ycr39nbzp8kh0000gn/T/9b8b4587-e1c6-4219-a679-a574b6c692fc/node_modules/memcache-plus/lib/client.js:79:14)
    at new Client (/private/var/folders/w4/0_jcj9dd67g3ycr39nbzp8kh0000gn/T/9b8b4587-e1c6-4219-a679-a574b6c692fc/node_modules/memcache-plus/lib/client.js:61:10)
    at Object.<anonymous> (/private/var/folders/w4/0_jcj9dd67g3ycr39nbzp8kh0000gn/T/9b8b4587-e1c6-4219-a679-a574b6c692fc/bin/api.js:68:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at validatePackage (/Users/m/.npm-packages/lib/node_modules/claudia/src/tasks/validate-package.js:15:15)
    at initEnvVarsFromOptions.then.then.then.then.then.then.then.dir (/Users/m/.npm-packages/lib/node_modules/claudia/src/commands/update.js:140:10)

**Comment by victorquinn** [comment]
Are you sure `process.env.memcache` has a value?

We should certainly fix the library to now blow up if an array with `[undefined]` is sent to the initialization but it really looks like your `process.env.memcache` is set to `undefined`

**Comment by msolovyov** [comment]
It is undefined during the Babel transpile. process.env is set once it's in AWS lambda.
