### ISSUE TITLE
Erroneous key length assertion

### ISSUE THREAD

**Issue by VitaliiB** [victorquinn/memcache-plus#65]
Hello, found a problem regarding this code:
```
misc.assert(key.length < 250, 'Key must be less than 250 characters long');
```

It asserts on character count rather than string byte length. So keys with characters that occupy 2 bytes will be measured incorrectly, leading to a runtime crash.

Steps to reproduce:
```
var MemcachePlus = require('memcache-plus');

var client = new MemcachePlus();
var key = Array(250).join('Я');

client.set(key, 'test');
```

Run with:
```
DEBUG=* node index.js
```

Output:
```
  memcache-plus:client Connect options { autodiscover: false,
  bufferBeforeError: 1000,
  disabled: false,
  hosts: null,
  reconnect: true,
  onNetError: [Function: onNetError],
  queue: true,
  netTimeout: 500,
  backoffLimit: 10000,
  maxValueSize: 1048576 } +0ms
  memcache-plus:client starting connection +3ms
  memcache-plus:client connecting to all hosts +0ms
  memcache-plus:connection connecting to host localhost:11211 +1ms
  memcache-plus:connection successfully (re)connected! +8ms
  memcache-plus:client flushing client write buffer +0ms
  memcache-plus:connection trying to flush buffer for localhost +3ms
  memcache-plus:connection sending: "set ЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯ..." +1ms
  memcache-plus:connection sending: "test" +0ms
  memcache-plus:connection got data: "CLIENT_ERROR bad command line format" and the queue now has "1" elements +1ms
  memcache-plus:connection responded and the queue now has "0" elements +1ms
  memcache-plus:connection got data: "ERROR" and the queue now has "0" elements +0ms
/home/vitalii/projects/mem-test/node_modules/memcache-plus/lib/connection.js:246
    if (deferred.type === 'autodiscovery') {
                 ^

TypeError: Cannot read property 'type' of undefined
    at Connection.read (/home/vitalii/projects/mem-test/node_modules/memcache-plus/lib/connection.js:246:18)
    at Carrier.emit (events.js:198:13)
    at /home/vitalii/projects/mem-test/node_modules/carrier/lib/carrier.js:24:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Correct check would be using https://nodejs.org/api/buffer.html#buffer_class_method_buffer_bytelength_string_encoding , i guess

**Comment by victorquinn** [comment]
Ahh, great catch! Will happily accept a PR for this

**Comment by oriamd** [comment]
@victorquinn Any idea why this error may cause an app to crash?

**Comment by victorquinn** [comment]
Not sure why that'd cause your app to crash, likely if you don't have proper exception handling it could wreak havoc on your app?

As I mentioned I'd gladly accept a PR to help fix this

Happily would accept a pr with Buffer, I don't think this library makes much sense outside of Node (for example it doesn't make sense to run in a browser). I can't remember why I didn't use Buffers in the first place but that makes a ton of sense

**Comment by oriamd** [comment]
@victorquinn 
This still does not catch the error 
```
const MemcachePlus = require('memcache-plus');
async function main(){
  try {
    const memCacheClient = new MemcachePlus({
        hosts: ['elastic-cache-test'],
        autodiscover: true,
    });
    const invalidKey = 'key with space';
    const response = await memCacheClient.set(invalidKey, 'value', 10)
    console.log(response);
  } catch (error) {
    console.error('Will not get here');
  }
}

try {
  main()
} catch (error) {
  console.error('Will not get here also (just for complete seal)');
}
```

All errors thrown in the Connection.read are unhandled since this code is running on stream callback

Maybe this function should wrapped in try/catch
