### ISSUE TITLE
Cachedump test fails.

### ISSUE THREAD

**Issue by RomanBurunkov** [victorquinn/memcache-plus#79]
Looks that something wrong with cachedump or it's tests.
On my local VM(node v12.20.1, memcached 1.5.6) cachedump test always fails:

```
1) Client cachedump should work gets cache metadata:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

```
Unhandled rejection TypeError: Cannot read property 'key' of undefined
    at /home/roman/memcache-plus/test/client.js:1267:36
    at tryCatcher (/home/roman/memcache-plus/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/roman/memcache-plus/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/roman/memcache-plus/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/roman/memcache-plus/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/roman/memcache-plus/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/roman/memcache-plus/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/roman/memcache-plus/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/roman/memcache-plus/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/roman/memcache-plus/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

```

**Comment by RomanBurunkov** [comment]
Tests has been passed after I've restarted memcached.

Looks wired since I had also tried to use get dumps with nc before restarting a daemon and it works good.
